name: Deploy

on:
   push:
      branches:
         - master
   pull_request:
   schedule:
      - cron: '0 0 * * *'

jobs:
   eslint:
      name: Check eslint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn check:eslint

   prettier:
      name: Check prettier
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn check:prettier

   typescript:
      name: Check typescript
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn check:typescript

   unit_tests:
      name: Unit tests
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint]
      steps:
         - uses: actions/checkout@v2
           with:
              submodules: 'recursive'
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - uses: actions/setup-dotnet@v1
           with:
              dotnet-version: '5.0.x'
         - run: yarn install
         - run:
              dotnet build
              submodules/osu-tools/PerformanceCalculator/PerformanceCalculator.csproj
              --configuration Release
         - run: echo "OSU_OAUTH_ID=${{ secrets.OSU_OAUTH_ID }}" >> .env
         - run: echo "OSU_OAUTH_TOKEN=${{ secrets.OSU_OAUTH_TOKEN }}" >> .env
         - run: echo "DOTNET_PATH=${{ secrets.DOTNET_PATH }}" >> .env
         - run: yarn tests:ci

   deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: [unit_tests]
      if: github.ref == 'refs/heads/master'
      steps:
         - uses: actions/checkout@v2
           with:
              submodules: 'recursive'
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - uses: actions/setup-dotnet@v1
           with:
              dotnet-version: '5.0.x'
         - run: yarn install
         - run: yarn build
         - run:
              dotnet build
              submodules/osu-tools/PerformanceCalculator/PerformanceCalculator.csproj
              --configuration Release
         - run: echo "OSU_OAUTH_ID=${{ secrets.OSU_OAUTH_ID }}" >> .env
         - run: echo "OSU_OAUTH_TOKEN=${{ secrets.OSU_OAUTH_TOKEN }}" >> .env
         - run: echo "DOTNET_PATH=${{ secrets.DOTNET_PATH }}" >> .env
         - run: echo "${{ secrets.SSHKEY }}" > key.pem
         - run: chmod 600 key.pem
         - run:
              rsync --inplace -ave "ssh -i key.pem -o StrictHostKeyChecking=no" . ${{
              secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/
         - run:
              ssh -i key.pem ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{
              secrets.DIR }} && pm2 startOrRestart pm2.config.json"
